In [1]:
import numpy as np
import pandas as pd
from numpy import random

# Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно
# Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.
# Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).
# Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
# Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.
# Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.
# Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?
# Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.
# Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?
# Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.
# Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно


In [2]:
a = np.arange(12,24,dtype=int)
a.flatten()
print(a)
a.shape


[12 13 14 15 16 17 18 19 20 21 22 23]


(12,)

In [3]:
x1 = random.choice(a, size=(2, 1))
print(x1)

[[20]
 [16]]


In [4]:
x2 = random.choice(a, size=(2, 2))
print(x2)

[[22 22]
 [13 15]]


In [5]:
x3 = random.choice(a, size=(2, 3))
print(x3)

[[14 17 13]
 [23 15 18]]


In [6]:
x4 = random.choice(a, size=(2, 4))
print(x4)

[[23 15 19 17]
 [22 14 16 22]]


In [7]:
x5 = random.choice(a, size=(3, 3))
print(x5)

[[15 14 16]
 [17 17 23]
 [14 23 19]]


In [8]:
x1 = np.reshape(a, (2,6))
print(x1)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [9]:
x2 = np.reshape(a, (3,4))
print(x2)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [10]:
x3 = np.reshape(a, (4,3))
print(x3)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [11]:
x4 = np.reshape(a, (6,2))
print(x4)

[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]


In [12]:
x5 = np.reshape(a, (12,1))
print(x5)
# Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным? - Нет

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [13]:
x1 = np.reshape(a, (-1,6))
print(x1)
x2 = np.reshape(a, (-1,4))
print(x2)
x3 = np.reshape(a, (-1,3))
print(x3)
x4 = np.reshape(a, (6,-1))
print(x4)
x5 = np.reshape(a, (12,-1))
print(x5)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [14]:
# Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.
my_mean = 0
my_std = 1

x = np.random.normal(loc=my_mean, scale=my_std, size=(3,4))
print(x)
x.mean(), x.std() #значения отличаются из-за размера выборки


[[-0.65431316  0.42513884  0.51645958 -1.26977795]
 [-0.38426243 -0.15278538  1.52618268  0.4779376 ]
 [-1.90601856 -0.36512483  0.92745608 -0.22581297]]


(-0.0904100407468413, 0.9035068565182784)

In [15]:
a = np.arange(20,0,-2)
a.shape

(10,)

In [16]:
#Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?
b = np.arange(20,1,-2)
b = np.array([b])
bt = b.T
bt
bt.shape

(10, 1)

In [17]:
# Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.
a0 = np.zeros([4,1])
a0

array([[0.],
       [0.],
       [0.],
       [0.]])

In [18]:
a1 = np.ones([5,1])
a1

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [19]:
a10 = np.concatenate((a0, a1), axis=0)
a10
v = np.append(a10, 0) # =)

In [20]:
v.size


10

In [21]:
# Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

a = np.arange(0,12,1)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
a.flatten()
matrixa = np.reshape(a, (4,3))
matrixa

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [23]:
matrixat = matrixa.T
matrixat

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [24]:
B = np.dot(matrixa,matrixat)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [25]:
B.shape

(4, 4)

In [26]:
from numpy import linalg as LA
# b_inv = LA.inv(matrixb)
# b_inv #LinAlgError: Singular matrix

In [27]:
# Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.
# Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно
np.random.seed(42)
c = np.random.randint(0, 16, size=16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

In [28]:
np.random.seed(42)
c = np.random.randint(0, 16, size=16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

In [29]:
# Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.
# Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [30]:
C = np.reshape(c, (4,4))
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [31]:
C = C * 10
C

array([[ 60,  30, 120, 140],
       [100,  70, 120,  40],
       [ 60,  90,  20,  60],
       [100, 100,  70,  40]])

In [32]:
D = np.add(B, C)
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [33]:
np.linalg.det(D) # Вычислите определитель

-28511999.999999944

In [34]:
np.linalg.matrix_rank(D) # Вычислите ранг

4

In [35]:
D_inv = np.linalg.inv(D) # Вычислите обратную матрицу
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

In [36]:
# Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [37]:
for i in D_inv:
        print(i)

[ 0.00935396  0.04486532  0.05897517 -0.07286055]
[-0.01503577 -0.00122896 -0.00192971  0.00967873]
[-0.00356692 -0.01782828 -0.04152146  0.04326178]
[ 0.00909091 -0.00181818  0.01272727 -0.01090909]


In [38]:
D_inv1 = D_inv > 0
D_inv1 * 1

array([[1, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 1, 0]])

In [39]:
E = np.where(D_inv1 == 1, B, C)
E


array([[  5,  14,  23, 140],
       [100,  70, 120, 122],
       [ 60,  90,  20, 212],
       [ 32, 100, 212,  40]])